"use client";
import MultiStepForm from "@/components/MultiStepForm";

const countries = [
  { value: "", label: "— Select country —", disabled: true },
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BQ", label: "Bonaire, Sint Eustatius and Saba" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvet Island" },
  { value: "BR", label: "Brazil" },
  { value: "IO", label: "British Indian Ocean Territory" },
  { value: "BN", label: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "CV", label: "Cabo Verde" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "KY", label: "Cayman Islands" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CX", label: "Christmas Island" },
  { value: "CC", label: "Cocos (Keeling) Islands" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo, Democratic Republic of the" },
  { value: "CK", label: "Cook Islands" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CW", label: "Curaçao" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FK", label: "Falkland Islands (Malvinas)" },
  { value: "FO", label: "Faroe Islands" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GF", label: "French Guiana" },
  { value: "PF", label: "French Polynesia" },
  { value: "TF", label: "French Southern Territories" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GD", label: "Grenada" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HM", label: "Heard Island and McDonald Islands" },
  { value: "VA", label: "Holy See" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IM", label: "Isle of Man" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "Korea (Democratic People's Republic of)" },
  { value: "KR", label: "Korea, Republic of" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Lao People's Democratic Republic" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NC", label: "New Caledonia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "NF", label: "Norfolk Island" },
  { value: "MK", label: "North Macedonia" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine, State of" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PN", label: "Pitcairn" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Qatar" },
  { value: "RE", label: "Réunion" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russian Federation" },
  { value: "RW", label: "Rwanda" },
  { value: "BL", label: "Saint Barthélemy" },
  {
    value: "SH",
    label: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "MF", label: "Saint Martin (French part)" },
  { value: "PM", label: "Saint Pierre and Miquelon" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SX", label: "Sint Maarten (Dutch part)" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
  },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SJ", label: "Svalbard and Jan Mayen" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Türkiye" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TC", label: "Turks and Caicos Islands" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UM", label: "United States Minor Outlying Islands" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Viet Nam" },
  { value: "VG", label: "Virgin Islands (British)" },
  { value: "VI", label: "Virgin Islands (U.S.)" },
  { value: "WF", label: "Wallis and Futuna" },
  { value: "EH", label: "Western Sahara" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

const STEPS = [
  {
    id: "personal-details",
    title: "",
    desc: "",

    fields: [
      {
        type: "group",
        label: "Full Name",
        fields: [
          {
            label: "First Name",
            name: "firstName",
            required: true,
            placeholder: "Enter your first name",
          },
          {
            label: "Middle Name",
            name: "middleName",
            placeholder: "Enter your middle name",
          },
          {
            label: "Last Name",
            name: "lastName",
            required: true,
            placeholder: "Enter your last name",
          },
        ],
      },
      {
        label: "Surname at birth / previous surnames",
        name: "surnameAtBirth",
        placeholder: "Enter any previous surnames if applicable",
        fullWidth: true,
      },
      {
        label: "Occupation",
        name: "occupation",
        required: true,
        placeholder: "What do you currently do?",
        fullWidth: true,
      },
      {
        label: "Date of birth",
        name: "dateOfBirth",
        type: "date",
        required: true,
      },
      {
        label: "Place of birth",
        name: "placeOfBirth",
        required: true,
        placeholder: "e.g. Apatin, Serbia",
        fullWidth: true,
      },
      {
        label: "Country / region of birth",
        name: "countryOfBirth",
        type: "select",
        required: true,
        placeholder: "— Select country —",
        options: countries,
      },
      {
        label: "Nationality at birth (if different)",
        name: "nationalityAtBirth",
        type: "select",
        placeholder: "— Select country —",
        options: countries,
      },
      {
        label: "Gender",
        name: "gender",
        type: "radio-group",
        required: true,
        fullWidth: true,
        options: [
          { value: "male", label: "Male" },
          { value: "female", label: "Female" },
          { value: "non_binary", label: "Non-binary" },
          { value: "prefer_not_to_say", label: "Prefer not to say" },
        ],
      },
      {
        label: "Marital status",
        name: "maritalStatus",
        type: "radio-group",
        required: true,
        fullWidth: true,
        options: [
          { value: "single", label: "Single" },
          { value: "married", label: "Married" },
          { value: "divorced", label: "Divorced" },
          { value: "separated", label: "Separated" },
          { value: "widowed", label: "Widower/Widow" },
          { value: "other", label: "Other" },
        ],
      },
    ],
  },
  {
    id: "contact",
    title: "Contact Information",
    desc: "",
    fields: [
      {
        label: "Email",
        name: "email",
        type: "email",
        required: true,
        placeholder: "Email Address.",
      },
      {
        type: "group",
        label: "Address",
        fields: [
          {
            label: "Address Line 1",
            name: "addressLine1",
            required: true,
            placeholder: "Address Line 1",
            fullWidth: true,
          },
          {
            label: "Address Line 2",
            name: "addressLine2",
            placeholder: "Address Line 2",
            fullWidth: true,
          },
        ],
      },
      {
        type: "group",
        fields: [
          {
            label: "City",
            name: "city",
            required: true,
            placeholder: "City",
            fullWidth: true,
          },
          {
            label: "State / Region",
            name: "state",
            placeholder: "State / Region",
            fullWidth: true,
          },
        ],
      },
      {
        label: "Zip Code",
        name: "zipCode",

        placeholder: "Zip",
      },
      {
        label: "Country / region of birth",
        name: "countryOfBirth",
        type: "select",
        required: true,
        placeholder: "— Select —",
        options: countries,
      },
      {
        label: "Phone/Mobile Number",
        placeholder: "Ensure to add your country code",
        name: "phoneNumber",
      },
    ],
  },

  {
    id: "identification",
    title: "Identification",
    desc: (
      <div>
        <span>
          Proof of identification (max file size 25MB) (e.g. birth certificate,
          driving license, foreign passport, etc).
        </span>
        <br />
        <br />
        <span>We keep all information private.</span>
      </div>
    ),
    fields: [
      {
        label: "File Upload",
        name: "idDocument",
        type: "file",
        required: true,
        fullWidth: true,
      },
    ],
  },
  {
    id: "general-questions",
    title: "General questions",
    fields: [
      {
        label: "What is your motivation to become an e-Resident?",
        name: "motivation",
        type: "textarea",
        required: true,
        fullWidth: true,
      },
    ],
  },
  {
    id: "additional-information",
    title: "Additional information",
    footerText: (
      <div>
        <h3 className="font-semibold">Price (e-Resident Basic)</h3>
        <p>Processing fee cost (converted from EUR to USD): $29.00</p>
      </div>
    ),
    fields: [
      {
        label:
          "Do you have any criminal convictions? If so, please provide information.",
        name: "criminalConvictions",
        type: "textarea",
        fullWidth: true,
      },
      {
        label:
          "Do you have any previous e-Resident application rejections? If so, please provide when and why.",
        name: "previousRejections",
        type: "textarea",
        fullWidth: true,
      },
      {
        label: "Any relevant information you would like to provide?",
        name: "relevantInformation",
        type: "textarea",
        fullWidth: true,
      },
      {
        label:
          "I hereby declare that the information provided in this application is true and accurate to the best of my knowledge. I give permission for this application information to be stored in the nations database and I consent to the processing of my personal data for e-Residency purposes and understand that the information may be subject to verification.",
        name: "declaration",
        type: "radio-group",
        required: true,
        fullWidth: true,
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" },
        ],
      },
      {
        placeholder:
          "I have read and agree to the Terms and Conditions and Privacy Policy",
        name: "termsAgreement",
        type: "checkbox",
        required: true,
      },
      {
        type: "text",
        label: "Notice",
        placeholder: `Once you have submitted your application, it can take up to 14 days for a response on your e-Resident application. Due to the amount of applicants to upkeep our systems, we charge a processing fee. All proceeds go into the Verdisian Government to help build the nation. Please ensure that your application is well-made. Refunds are not permitted if your application is declined.`,
      },
    ],
  },
];

export default function BasicFormScreen() {
  return (
    <div className="max-w-6xl mx-auto my-12 px-4 md:px-0">
      <h1 className="text-3xl font-bold mb-6 text-left">
        e-Resident Basic Application
      </h1>
      <MultiStepForm STEPS={STEPS} />
    </div>
  );
}
